# Generated by Django 4.0 on 2021-12-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
