# Generated by Django 4.0 on 2021-12-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(default='fuck', max_length=150, verbose_name='f_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(default='dummy', max_length=150, verbose_name='l_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='35454', max_length=150, verbose_name='mobile'),
            preserve_default=False,
        ),
    ]
