# Generated by Django 4.0 on 2021-12-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_f_name_user_l_name_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_amount',
            field=models.FloatField(default=0, verbose_name='loan_amount'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.IntegerField(default=0, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=15, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='username'),
        ),
    ]
