# Generated by Django 4.0 on 2021-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_f_name_remove_user_l_name_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_payable',
            field=models.FloatField(default=0, verbose_name='total_payable'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.FloatField(default=0, verbose_name='time'),
        ),
    ]
