# Generated by Django 4.0 on 2021-12-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_total_payable_alter_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_payable',
            field=models.FloatField(default=0, verbose_name='time'),
        ),
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_amount', models.FloatField()),
                ('loanee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
