# Generated by Django 4.0 on 2021-12-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_total_payable_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='loanee_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='total_payable',
            field=models.FloatField(default=0, verbose_name='total_payable'),
        ),
    ]
